#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
include_filters:
  - tag:Name:
      - 'SingleInstanceStack/c7i-metal-4xl'
hostnames:
  - name: tag:Name
    separator: ''
compose:
  # Use the private IP address to connect to the host
  # (note: this does not modify inventory_hostname, which is set via I(hostnames))
  ansible_host: public_ip_address
keyed_groups:
  - key: tag:Name
    separator: ''

